# Generated by Django 5.0.2 on 2025-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Número de teléfono identificador de la compañía",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
