# Generated by Django 5.0.2 on 2025-09-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="drive_folder_id",
            field=models.CharField(
                blank=True,
                help_text="ID de la carpeta compartida en Google Drive",
                max_length=100,
                null=True,
            ),
        ),
    ]
