# Generated by Django 5.2.6 on 2025-09-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord')], help_text='Tipo de fuente de mensajería', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la fuente está activa')),
                ('api_key', models.CharField(help_text='API Key para autenticación', max_length=255, unique=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL del webhook para recibir mensajes', null=True)),
                ('additional1', models.TextField(blank=True, help_text='Campo adicional 1 - Ej: Twilio Account SID, Telegram Bot Token', null=True)),
                ('additional2', models.TextField(blank=True, help_text='Campo adicional 2 - Ej: Twilio Auth Token, Telegram Chat ID', null=True)),
                ('additional3', models.TextField(blank=True, help_text='Campo adicional 3 - Ej: Twilio Phone Number, Telegram Webhook URL', null=True)),
                ('additional4', models.TextField(blank=True, help_text='Campo adicional 4 - Ej: Configuraciones adicionales, tokens de acceso', null=True)),
                ('additional5', models.TextField(blank=True, help_text='Campo adicional 5 - Ej: Configuraciones específicas de la integración', null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'sources',
                'ordering': ['name'],
            },
        ),
    ]
