# Generated by Django 5.2.6 on 2025-09-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text='Nombre del archivo', max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], help_text='Tipo de archivo', max_length=20)),
                ('file_size', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('sender_number', models.CharField(help_text='Número de teléfono del remitente', max_length=20)),
                ('drive_file_id', models.CharField(help_text='ID del archivo en Google Drive', max_length=255, unique=True)),
                ('drive_shared_link', models.URLField(help_text='Enlace compartido del archivo en Google Drive')),
                ('drive_folder_path', models.CharField(help_text='Ruta de la carpeta en Google Drive', max_length=500)),
                ('source', models.ForeignKey(help_text='Fuente de donde proviene el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sources.source')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
            },
        ),
    ]
