# Generated by Django 5.0.2 on 2025-09-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentmessages", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Compañía del usuario",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content_type",
            field=models.CharField(
                blank=True, help_text="Tipo MIME del archivo", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_id",
            field=models.CharField(
                blank=True,
                help_text="ID del mensaje en la plataforma",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_text",
            field=models.TextField(
                blank=True, help_text="Texto del mensaje", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que envió el mensaje",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="drive_file_id",
            field=models.CharField(
                blank=True, help_text="ID del archivo en Google Drive", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="drive_folder_path",
            field=models.CharField(
                blank=True,
                help_text="Ruta de la carpeta en Google Drive",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="drive_shared_link",
            field=models.URLField(
                blank=True, help_text="Enlace compartido del archivo en Google Drive"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, help_text="Tamaño del archivo en bytes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("document", "Document"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                help_text="Tipo de archivo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="filename",
            field=models.CharField(
                blank=True, help_text="Nombre del archivo", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_number",
            field=models.CharField(
                blank=True,
                help_text="Número de teléfono del remitente",
                max_length=20,
                null=True,
            ),
        ),
    ]
